name: Build and Deploy to VPS

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 20
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20'

    - name: Build app with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t mitsenisa/digital-waiter:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mitsenisa/digital-waiter:latest

    - name: SSH to VPS and deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22222
        script: |
          cd /home/${{ secrets.SERVER_USER }}/digital-waiter
          docker compose pull
          docker compose down
          docker compose up -d  
