name: Mirror to GitLab
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.sberlab.nsu.ru/a.timoshchuk/digital-waiter.git
          git push --mirror gitlab